version: "3"

tasks:
  gen:translator:
    cmds:
      - |
        protoc -I proto proto/v1/translator/translator.proto \
        --go_out=./gen/go \
        --go-grpc_out=./gen/go \
        --go_opt=paths=source_relative \
        --go-grpc_opt=paths=source_relative
